import { useEffect, useState } from 'react';
import Button from '../../components/UI/Button';
import DataTable from '../../components/UI/DataTable';
import Input from '../../components/UI/Input';
import Loading from '../../components/UI/Loading';
import Modal from '../../components/UI/Modal';
import Pagination from '../../components/UI/Pagination';
import Toast from '../../components/UI/Toast';
import CompactAlert from '../../components/UI/CompactAlert';
import { employeeBaselines, payrollBaselineConfiguration, saveEmployeeBaseline, savePayrollBaselineConfiguration } from '../../services/payrollBaselineApi';

const employeeFields = [['gaji_pokok', 'Gaji Pokok'], ['uang_harian', 'Uang Harian'], ['tunj_antar_cabang', 'Tunj. Antar Cabang'], ['tunj_komunikasi', 'Tunj. Komunikasi'], ['tunj_kost', 'Tunj. Kost'], ['tunj_jabatan', 'Tunj. Jabatan'], ['thr', 'THR'], ['dasar_perhitungan_bpjs_tk', 'Dasar Upah BPJS TK (bukan iuran)'], ['dasar_perhitungan_bpjs_kes', 'Dasar Upah BPJS KES (bukan iuran)'], ['potongan_alpha', 'Potongan Alpha']];
const configurationGroups = [
  ['Tunjangan', [['jht_pens', 'TK JHT & Pensiun'], ['jkk_jkm', 'JKK & JKM'], ['bpjs_p', 'BPJS-P'], ['tunj_bpjs', 'Tunj. BPJS', true]]],
  ['Potongan', [['potgn_tk', 'Potongan TK'], ['tunj_prshan', 'Tunjangan Perusahaan', true], ['potgn_kes', 'Potongan Kesehatan']]],
  ['Lainnya', [['lembur_hari_kerja_rate', 'Lembur Hari Kerja (Rp/Jam)'], ['lembur_hari_libur_multiplier', 'Lembur Hari Libur (Pengali Uang Harian)'], ['insentif_default', 'Insentif Default']]],
];
const percentageFields = new Set(['jht_pens', 'jkk_jkm', 'bpjs_p', 'tunj_bpjs', 'potgn_tk', 'tunj_prshan', 'potgn_kes', 'insentif_default']);
const rupiah = value => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value || 0);
const configValue = (key, value) => key === 'lembur_hari_kerja_rate' ? rupiah(value) : percentageFields.has(key) ? `${Number(value || 0).toLocaleString('id-ID', { maximumFractionDigits: 2 })}%` : `${Number(value || 0).toLocaleString('id-ID', { maximumFractionDigits: 2 })}×`;
const pts = ['DPL', 'TOPI', 'KORP BKS', 'KORP SMRG', 'SRT PM', 'SRT CKRG', 'SRT SMRG', 'SRT SBY'];

export default function PayrollBaseline() {
  const [rows, setRows] = useState([]), [meta, setMeta] = useState(), [search, setSearch] = useState(''), [pt, setPt] = useState(''), [page, setPage] = useState(1);
  const [config, setConfig] = useState(), [configDraft, setConfigDraft] = useState(null), [employee, setEmployee] = useState(null), [error, setError] = useState(''), [toast, setToast] = useState(''), [busy, setBusy] = useState(true);
  const load = async () => { setBusy(true); setError(''); try { const [employees, configuration] = await Promise.all([employeeBaselines({ search, pt, page }), payrollBaselineConfiguration()]); setRows(employees.data.data); setMeta(employees.data.meta); setConfig(configuration.data.data); } catch (e) { setError(e.response?.data?.message || 'Data baseline payroll tidak dapat dimuat.'); } finally { setBusy(false); } };
  useEffect(() => { load(); }, [page]);
  const saveEmployee = async event => { event.preventDefault(); try { await saveEmployeeBaseline(employee.employee_id, { ...Object.fromEntries(employeeFields.map(([key]) => [key, Number(employee[key] || 0)])), incentive_eligible: !!employee.incentive_eligible, pt: employee.pt, title: employee.title || null, family_status: employee.family_status || null }); setEmployee(null); setToast('Baseline payroll karyawan berhasil disimpan.'); load(); } catch (e) { setError(e.response?.data?.message || 'Baseline karyawan tidak dapat disimpan.'); } };
  const saveConfiguration = async event => { event.preventDefault(); try { const response = await savePayrollBaselineConfiguration(Object.fromEntries(configurationGroups.flatMap(([, fields]) => fields.filter(([, , readonly]) => !readonly).map(([key]) => [key, Number(configDraft[key] || 0)])))); setConfig(response.data.data); setConfigDraft(null); setToast('Master baseline payroll berhasil diperbarui.'); } catch (e) { setError(e.response?.data?.message || 'Master baseline payroll tidak dapat disimpan.'); } };
  const columns = [
    { key: 'employee_name', label: 'Nama Karyawan' }, { key: 'employee_number', label: 'ID Karyawan' }, { key: 'tax_number', label: 'NIK', render: row => row.tax_number || '-' }, { key: 'pt', label: 'PT' }, { key: 'title', label: 'Title' }, { key: 'family_status', label: 'Family Status' }, { key: 'gaji_pokok', label: 'Gaji Pokok', render: row => rupiah(row.gaji_pokok) }, { key: 'uang_harian', label: 'Uang Harian', render: row => rupiah(row.uang_harian) }, { key: 'tunj_antar_cabang', label: 'Tunj. Antar Cabang', render: row => rupiah(row.tunj_antar_cabang) }, { key: 'tunj_komunikasi', label: 'Tunj. Komunikasi', render: row => rupiah(row.tunj_komunikasi) }, { key: 'tunj_kost', label: 'Tunj. Kost', render: row => rupiah(row.tunj_kost) }, { key: 'tunj_jabatan', label: 'Tunj. Jabatan', render: row => rupiah(row.tunj_jabatan) }, { key: 'thr', label: 'THR', render: row => rupiah(row.thr) }, { key: 'dasar_perhitungan_bpjs_tk', label: 'TK', render: row => rupiah(row.dasar_perhitungan_bpjs_tk) }, { key: 'dasar_perhitungan_bpjs_kes', label: 'KES', render: row => rupiah(row.dasar_perhitungan_bpjs_kes) }, { key: 'potongan_alpha', label: 'Potongan Alpha', render: row => rupiah(row.potongan_alpha) }, { key: 'action', label: 'Tindakan', render: row => <button className="text-sky-700" onClick={() => setEmployee({ ...row })}>Ubah</button> },
  ];

  return <section className="operational-page baseline-page">
    <div className="operation-header"><div><p className="operation-kicker">Konfigurasi · master payroll</p><h1>Baseline Payroll</h1><p>Kelola aturan perusahaan dan komponen gaji setiap karyawan.</p></div><span className="operation-step">Nilai digunakan saat payroll dihitung</span></div>
    <CompactAlert message={error} />
    {config && <section className="baseline-overview"><div className="baseline-overview__heading"><div><p className="baseline-section-label">Aturan perusahaan</p><h2>Master Baseline Payroll</h2><p>Persentase dan tarif aktif yang menjadi acuan perhitungan payroll.</p></div><Button onClick={() => setConfigDraft({ ...config })}>Edit Master Baseline</Button></div><div className="baseline-overview__groups">{configurationGroups.map(([title, fields]) => <div className="baseline-rule-group" key={title}><h3>{title}</h3><dl>{fields.map(([key, label, readonly]) => <div key={key}><dt>{label}{readonly && <span>Otomatis</span>}</dt><dd>{configValue(key, config[key])}</dd></div>)}</dl></div>)}</div></section>}
    <section className="salary-components"><div className="salary-components__heading"><div><p className="baseline-section-label">Nilai per karyawan</p><h2>Master Data Komponen Gaji</h2><p>Atur gaji pokok, tunjangan, BPJS, dan potongan untuk setiap karyawan.</p></div></div><form className="baseline-filters" onSubmit={event => { event.preventDefault(); setPage(1); load(); }}><Input aria-label="Cari karyawan" placeholder="Cari nama atau NIK" value={search} onChange={event => setSearch(event.target.value)}/><select aria-label="Filter PT" value={pt} onChange={event => setPt(event.target.value)} className="rounded border border-slate-300 px-3"><option value="">Semua PT</option>{pts.map(value => <option key={value}>{value}</option>)}</select><Button>Cari</Button></form>{busy ? <Loading label="Memuat baseline payroll…"/> : <><DataTable columns={columns} rows={rows}/><Pagination meta={meta} onPage={setPage}/></>}</section>
    <Modal open={!!configDraft} wide title="Edit Master Baseline Payroll" onClose={() => setConfigDraft(null)}>{configDraft && <form onSubmit={saveConfiguration} className="baseline-config-form"><p className="baseline-modal-note">Perubahan ini akan digunakan pada perhitungan payroll berikutnya. Nilai bertanda otomatis dihitung oleh sistem.</p>{configurationGroups.map(([title, fields]) => <fieldset key={title}><legend>{title}</legend><div className="grid gap-4 md:grid-cols-2">{fields.map(([key, label, readonly]) => <Input key={key} label={label} type="number" min="0" step="0.01" readOnly={readonly} value={configDraft[key] ?? ''} onChange={event => setConfigDraft({ ...configDraft, [key]: event.target.value })} className={readonly ? 'bg-slate-100 text-slate-500' : ''}/>)}</div></fieldset>)}<div className="flex justify-end gap-2"><Button type="button" className="bg-slate-200 text-slate-800" onClick={() => setConfigDraft(null)}>Batal</Button><Button>Simpan Perubahan</Button></div></form>}</Modal>
    <Modal open={!!employee} title="Ubah Baseline Payroll" onClose={() => setEmployee(null)}>{employee && <form className="grid gap-3 md:grid-cols-2" onSubmit={saveEmployee}><Input label="Nama Karyawan" readOnly value={employee.employee_name} className="bg-slate-100 text-slate-500"/><Input label="NIK" readOnly value={employee.tax_number || '-'} className="bg-slate-100 text-slate-500"/><Input label="PT" readOnly value={employee.pt || ''} className="bg-slate-100 text-slate-500"/><Input label="Title" value={employee.title || ''} onChange={event => setEmployee({ ...employee, title: event.target.value })}/><label className="block text-sm font-medium text-slate-700">Family Status<select value={employee.family_status || ''} onChange={event => setEmployee({ ...employee, family_status: event.target.value })} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2"><option value="">Pilih Family Status</option>{['TK/0', 'TK/1', 'TK/2', 'TK/3', 'K/0', 'K/1', 'K/2', 'K/3'].map(value => <option key={value}>{value}</option>)}</select></label><label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={!!employee.incentive_eligible} onChange={event => setEmployee({ ...employee, incentive_eligible: event.target.checked })}/>Berhak menerima insentif kehadiran</label>{employeeFields.map(([key, label]) => <Input key={key} label={label} type="number" min="0" step="0.01" required value={employee[key] ?? 0} onChange={event => setEmployee({ ...employee, [key]: event.target.value })}/>)}<div className="flex justify-end gap-2 md:col-span-2"><Button type="button" className="bg-slate-200 text-slate-800" onClick={() => setEmployee(null)}>Batal</Button><Button>Simpan</Button></div></form>}</Modal>
    <Toast message={toast}/>
  </section>;
}
